// Automatically generated by astro-icon
// 4b8379d9476c5da43a6d9f44eb84be0a1a9897ca1bb0c4a12a65522bb4c6242a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bi:github"
		| "bi:instagram"
		| "bi:envelope"
		| "ri:youtube-fill";
}